#!/usr/bin/env python
import argparse # optparse is deprecated
from itertools import islice # slicing for iterators
import pdb
from nltk.corpus import wordnet as wn
 

def word_matches(h, ref):
    return sum(1 for w in h if w in ref)

def meteor(h, ref, alpha):
    precision = word_matches(h, ref) / float(len(ref))
    recall = word_matches(h, ref) / float(len(h))

    if recall == 0 and precision == 0:
        return 0
    return (precision * recall) / ((1 - alpha) * recall + alpha * precision)

 
def main():
    parser = argparse.ArgumentParser(description='Evaluate translation hypotheses.')
    parser.add_argument('-i', '--input', default='data/hyp1-hyp2-ref',
            help='input file (default data/hyp1-hyp2-ref)')
    parser.add_argument('-n', '--num_sentences', default=None, type=int,
            help='Number of hypothesis pairs to evaluate')
    parser.add_argument('-a', '--alpha', default=0, type=float,
            help='alpha value for meteor')
    # note that if x == [1, 2, 3], then x[:None] == x[:] == x (copy); no need for sys.maxint
    opts = parser.parse_args()
 
    # we create a generator and avoid loading all sentences into a list
    def sentences():
        with open(opts.input) as f:
            for pair in f:
                yield [sentence.strip().split() for sentence in pair.split(' ||| ')]
 
    # note: the -n option does not work in the original code
    for h1, h2, ref in islice(sentences(), opts.num_sentences):
        rset = set(ref)
        syn_set = set()
        all_lsts = [wn.synsets(item) for item in rset] 
        for lst in all_lsts:
            for item in lst:
                if item not in syn_set:
                    syn_set.add(item)

        pdb.set_trace()

        #determine whether to run METEOR or Adam Lopez's starter code
        if opts.alpha == 0:
            h1_match = word_matches(h1, rset)
            h2_match = word_matches(h2, rset)
        else:
            h1_match = meteor(h1, rset, opts.alpha) #word_matches(h1, rset)
            h2_match = meteor(h2, rset, opts.alpha) #word_matches(h2, rset)
        print(1 if h1_match > h2_match else # \begin{cases}
                (0 if h1_match == h2_match
                    else -1)) # \end{cases}
 
# convention to allow import of this file as a module
if __name__ == '__main__':
    main()
